apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-04-17T20:48:45Z"
  labels:
    app: currency-exchange
  name: currency-exchange
  namespace: default
  resourceVersion: "18242"
  uid: 8be6b913-a6d5-4f6d-9cd1-5a2944184a32
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.101.250.13
  clusterIPs:
  - 10.101.250.13
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30184
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: currency-exchange
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - hostname: localhost
